### ISSUE TITLE
翻译问题

### ISSUE THREAD

**Issue by TATangZY** [MicrosoftDocs/cpp-docs.zh-cn#101]
个人感觉C++关键字不应该翻译为中文，如 "double" 翻译为”双“，for 循环翻译为”为“循环。非常不直观。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a22c8bac-8d8a-a9c8-4167-26f21f7e4a78
* Version Independent ID: cf220c62-e61f-c64e-8e68-075d9273e305
* Content: [C++ 类型系统（现代 C++）](https://docs.microsoft.com/zh-cn/cpp/cpp/cpp-type-system-modern-cpp?view=vs-2019)
* Content Source: [docs/cpp/cpp-type-system-modern-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/cpp/cpp-type-system-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @TATangZY
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by TATangZY** [comment]
> Hello, @TATangZY
> 
> Thank you for your feedback.
> 
> We are actively reviewing your comments and will get back to you soon.
> 
> Kind regards,
> Microsoft DOCS International Team

Should I comment in English?
I meant that C++ keywords should not be translated into Chinese. For example, "double" was translated into "双", "for" loop was translated into "为" loop, which is very unnatural.

**Comment by CeciAc** [comment]
你好，@TATangZY

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：  https://docs.microsoft.com/zh-cn/cpp/cpp/cpp-type-system-modern-cpp?view=vs-2019

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
