### ISSUE TITLE
类型字段字符文档中类型字符的翻译错误

### ISSUE THREAD

**Issue by encofcomic** [MicrosoftDocs/cpp-docs.zh-cn#102]
在类型字段字符（Type field characters）部分，单字节或多字节字符串对应的类型字符（Type character） 's' 被误翻译为了秒，此处字符无需翻译。
根据 creference， Signaling NaN  推荐翻译为 发信NaN

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 78bd3fde-7eae-a126-f330-563d912a1fab
* Version Independent ID: b6f2df29-3154-05ec-4c9b-9dbd8c316dd3
* Content: [格式规范语法：printf 和 wprintf 函数](https://docs.microsoft.com/zh-cn/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2019)
* Content Source: [docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @encofcomic
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@encofcomic

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2019

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
