### ISSUE TITLE
发现错误

### ISSUE THREAD

**Issue by insulations** [MicrosoftDocs/cpp-docs.zh-cn#106]
printf的语法int printf(
   const char *format [,
   argument]...
);此处的[与,书写反了，而且不仅仅是这个，语法一栏中的所有类似地方全部打错了。
The syntax of "printf" is wrong, "," and "[" are written on the wrong sides.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a4a1655b-7dbc-9a8a-e8c5-5232f86c5827
* Version Independent ID: daa02428-6f8c-597e-fb24-632148f988e0
* Content: [printf、_printf_l、wprintf、_wprintf_l](https://docs.microsoft.com/zh-cn/cpp/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l?redirectedfrom=MSDN&view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/c-runtime-library/reference/printf-printf-l-wprintf-wprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @insulations
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by corob-msft** [comment]
@insulations 

The syntax used here is confusing. It differs from function declaration syntax. In this case, the square brackets and ellipsis (`[ ]...`) indicates "zero or more" of what's inside.

**Comment by insulations** [comment]
Ok,I have known it.Thank you!



---原始邮件---
发件人: "Colin Robertson"<notifications@github.com&gt;
发送时间: 2019年12月2日(周一) 下午5:40
收件人: "MicrosoftDocs/cpp-docs.zh-cn"<cpp-docs.zh-cn@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"insulations"<940074460@qq.com&gt;;
主题: Re: [MicrosoftDocs/cpp-docs.zh-cn] 发现错误 (#106)



@insulations
 
The syntax used here is confusing. It differs from function declaration syntax. In this case, the square brackets and ellipsis ([ ]...) indicates "zero or more" of what's inside.

**Comment by CeciAc** [comment]
Hello, @insulations 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
