### ISSUE TITLE
"从 Visual Studio 2015 开始，不再这种情况"翻译有欠缺

### ISSUE THREAD

**Issue by scofined** [MicrosoftDocs/cpp-docs.zh-cn#122]
"从 Visual Studio 2015 开始，不再这种情况。"
第一段落的如上语句,翻译存在问题,应该改成"不再存在这种情况"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 12d45abb-3fbc-b262-29ca-8f5c4e7b49b2
* Version Independent ID: 3c087dd0-b858-f9fe-b9e6-81d1d336de68
* Content: [通用 CRT 部署](https://docs.microsoft.com/zh-cn/cpp/windows/universal-crt-deployment?view=vs-2019#feedback)
* Content Source: [docs/windows/universal-crt-deployment.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/windows/universal-crt-deployment.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @scofined
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
你好，@scofined

感谢你的反馈。有问题的页面是采用机器翻译的，因此不一定容易理解。我们最近在右侧添加了“阅读英文版”选项，无需更改语言设置即可切换到的英文版。  

深深的祝福，  

Microsoft DOCS International Team
