### ISSUE TITLE
我想知道如何解决这个问题

### ISSUE THREAD

**Issue by ATBHI** [MicrosoftDocs/cpp-docs.zh-cn#123]
#include <windows.h>

int WINAPI WinMain(HINSTANCE hInstance, HIBERFILE_BUCKET hPreInstance, LPSTR IpCmdLine, int nCmdShow)
{
	return 0;
}

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 87dcf611-7ff5-4c49-fff8-5a2c6bd41e87
* Version Independent ID: 8934f4c7-3b06-af8f-7c1a-9326c397f26e
* Content: [编译器错误 C2731](https://docs.microsoft.com/zh-cn/cpp/error-messages/compiler-errors-2/compiler-error-c2731?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(C2731)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c2731.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/error-messages/compiler-errors-2/compiler-error-c2731.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @ATBHI
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by corob-msft** [comment]
@ATBHI 
The `WinMain` function must have the same signature declared in \<winbase.h>, which is included by \<windows.h>. `HIBERFILE_BUCKET` is both the wrong type and the wrong size for the function signature. In C++, this parameter type makes the function signature different. The compiler thinks you overloaded the `WinMain` function. Change the second parameter to type `HINSTANCE` to fix the problem.

**Comment by ATBHI** [comment]
Thank you very much for helping me solve this problem,but i don't know how to change it.Because i just a Programming small white.
Thank you!
