### ISSUE TITLE
有问题

### ISSUE THREAD

**Issue by qcc-gif** [MicrosoftDocs/cpp-docs.zh-cn#124]
我定义了啊，还是显示未定义

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b490e067-2537-cbe0-d630-2f1004362ffa
* Version Independent ID: 74b4577c-6948-0a13-5b95-2d15d7e986d8
* Content: [编译器错误 C2027](https://docs.microsoft.com/zh-cn/cpp/error-messages/compiler-errors-1/compiler-error-c2027?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DZH-CN%26k%3Dk(C2027)%26rd%3Dtrue&view=vs-2019#feedback)
* Content Source: [docs/error-messages/compiler-errors-1/compiler-error-c2027.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/error-messages/compiler-errors-1/compiler-error-c2027.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @qcc-gif
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by qcc-gif** [comment]
qcc
1633752749@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"srvbpigh"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月28日(星期六) 中午12:42
收件人:&nbsp;"MicrosoftDocs/cpp-docs.zh-cn"<cpp-docs.zh-cn@noreply.github.com&gt;;
抄送:&nbsp;"qcc"<1633752749@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MicrosoftDocs/cpp-docs.zh-cn] 有问题 (#124)





 
Hello, @qcc-gif
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.
 
Kind regards,
 Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@qcc-gif 

我们诚挚感谢你的评论，我们会努力改善你在 docs.microsoft.com 的使用体验。但是，为了解决你的反馈，我们需要更多信息。你可以提供更为详细的信息并阐明你的评论吗？ 

顺祝商祺！ 

Microsoft DOCS 国际团队

**Comment by qcc-gif** [comment]
问题已经解决了，是我自己的问题，非常感谢您的反馈


qcc
1633752749@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Cecilia Acevedo"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 上午9:10
收件人:&nbsp;"MicrosoftDocs/cpp-docs.zh-cn"<cpp-docs.zh-cn@noreply.github.com&gt;;
抄送:&nbsp;"qcc"<1633752749@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MicrosoftDocs/cpp-docs.zh-cn] 有问题 (#124)





 
Reopened #124.

**Comment by V-vafune** [comment]
你好，@qcc-gif  

非常感谢你提供反馈。很高兴我们的文档满足你的期望。  

欢迎提供宝贵的反馈，以便我们继续改进体验。  

深深的祝福，  
Microsoft DOCS International Team
