### ISSUE TITLE
纠错

### ISSUE THREAD

**Issue by ICARUSDAI** [MicrosoftDocs/cpp-docs.zh-cn#125]
“在前面的示例中，使用指向 GetState 类型的指针调用虚函数 VFuncBase 将调用 VFuncDerived::GetState，并且会将 GetState 视为公共的。 但是，使用指向 GetState 类型的指针调用 VFuncDerived 是访问控制冲突，因为在 GetState 类中将 VFuncDerived 声明为私有的。”
应为
“在前面的示例中，使用指向 VFuncBase 类型的指针调用虚函数GetState  将调用 VFuncDerived::GetState，并且会将 GetState 视为公共的。 但是，使用指向  VFuncDerived类型的指针调用GetState  是访问控制冲突，因为在 VFuncDerived类中将 GetState  声明为私有的。”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d87522c9-3acc-b2f5-415e-30c067d42885
* Version Independent ID: da3d2e37-a7c1-d0b8-9fc7-95992e020cac
* Content: [成员访问控制 (C++)](https://docs.microsoft.com/zh-cn/cpp/cpp/member-access-control-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/member-access-control-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/cpp/member-access-control-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @ICARUSDAI
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@ICARUSDAI

感谢你的发布内容。 

当前不接受有关机器翻译内容的翻译问题的发布内容。 

我们重视你对人工翻译内容（用于训练机器翻译引擎）的反馈和建议，你的参与将逐渐提高人工翻译和机器翻译的质量。 

人工翻译主题可以通过每个内容文件标题中的 ms.translationtype 元数据值“HT”与机器翻译主题（使用“MT”作为元数据值）区别开。 

非常感谢你的支持。 

Microsoft DOCS 全球体验团队
