### ISSUE TITLE
Lots of translation problems in this page

### ISSUE THREAD

**Issue by BlurringShadow** [MicrosoftDocs/cpp-docs.zh-cn#126]
1. standard library class and function names shouldn't be translated into Chinese. There are:
std：：字符串 
标准：：矢量
分值：：变数
std：：原子
...
And wrong colons '：'.
2. "C++11 引入了用于变量、函数和模板声明的自动关键字。 自动告诉编译器推断对象的类型，这样您就不必显式键入它。 当推算类型是嵌套模板时，自动特别有用"
In this section, 
Keyword "auto" is inappropriately translated into "自动";
"推导" is better than "推算".
3. At the page beginning "它可以在最高抽象级别工作，在硅级别下". I prefer "它既可以在最高抽象层次下使用，也能深入底层硬件操作"(personal translation suggestion).
4. "缺点表达式" should be "常量表达式"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: b83658b4-2e2f-f617-174d-6741575beca3
* Version Independent ID: 09fd3e8d-d0e2-bfe9-ebdf-24b7c2b5db9e
* Content: [欢迎回到C++ - 现代C++](https://docs.microsoft.com/zh-cn/cpp/cpp/welcome-back-to-cpp-modern-cpp?view=vs-2019#constexpr-expressions-instead-of-macros)
* Content Source: [docs/cpp/welcome-back-to-cpp-modern-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/cpp/welcome-back-to-cpp-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @BlurringShadow
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-radelg** [comment]
Hello @<contributor's GITHUB name>:

Thank you for your contribution.

Contributions on translation problems against machine translated content are currently not accepted.

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations.

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file.

Many thanks for your support.

Microsoft DOCS Global Experience Team

cc @JasonCard
