### ISSUE TITLE
“event_receiver”: 未找到特性	

### ISSUE THREAD

**Issue by DevinChen1** [MicrosoftDocs/cpp-docs.zh-cn#128]
错误	C2337	“event_receiver”: 未找到特性	 

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 31f09726-cc61-858c-3a0d-4fc80a0288b0
* Version Independent ID: d0ef017b-b938-4401-6c9a-1405bd60e096
* Content: [本机 C++ 中的事件处理](https://docs.microsoft.com/zh-cn/cpp/cpp/event-handling-in-native-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/event-handling-in-native-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/cpp/event-handling-in-native-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @DevinChen1
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@DevinChen1

非常感谢您的贡献。此反馈与产品相关，请使用“文档”页底部的“提供产品反馈”按钮，记录你的建议。 

如果你有任何与文档相关的反馈，请通过此渠道进行记录。 

我们非常感谢你对我们的文章的贡献。 

Microsoft DOCS 国际团队
