### ISSUE TITLE
公共方法中有描述不对

### ISSUE THREAD

**Issue by venusprotein** [MicrosoftDocs/cpp-docs.zh-cn#154]
公共方法中有两处显示不对。
（1）CStringT::CompareNoCase的说明：原文“比较两个字符串)(不区分大小写”，原文中的括号使用不对；
（2）CStringT::CompareNoCase的下一条“CStringT::De)”属性名称写的不对，应该是“CStringT::Delete”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e0a9ec5a-f8e2-f739-1b39-74b4a775ee98
* Version Independent ID: c1eaf2d0-1cd3-25a1-c44d-3aae49be555b
* Content: [CStringT 类](https://docs.microsoft.com/zh-cn/cpp/atl-mfc-shared/reference/cstringt-class?view=msvc-160#delete)
* Content Source: [docs/atl-mfc-shared/reference/cstringt-class.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/atl-mfc-shared/reference/cstringt-class.md)
* Product: **visual-cpp**
* Technology: **cpp-mfc**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
I used a translation tool to try to understand what the issue was and I think I've addressed it. The fix will be live by Wednesday, 11/18
