### ISSUE TITLE
erro

### ISSUE THREAD

**Issue by gaoshuaiqi** [MicrosoftDocs/cpp-docs.zh-cn#160]
[在此处输入反馈]
-using namespace B;
+using namespace NamespaceB;

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: d735acb7-c62e-5162-0cd1-80ea78227287
* Version Independent ID: 3962a24d-f3d4-03d2-9769-eead54f772c7
* Content: [范围解析运算符：::](https://docs.microsoft.com/zh-cn/cpp/cpp/scope-resolution-operator?view=msvc-160)
* Content Source: [docs/cpp/scope-resolution-operator.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/cpp/scope-resolution-operator.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@gaoshuaiqi 

Thanks for the report. I've fixed the problem in the English source files. The translated version should be fixed in a few days.

感谢您的报告。 我已经在英文源文件中解决了这个问题。 翻译版本应在几天之内固定。
