### ISSUE TITLE
Chinese translation error

### ISSUE THREAD

**Issue by fililili** [MicrosoftDocs/cpp-docs.zh-cn#168]
in the article, it translate "/ZI cannot be used with /GL" to "/Zi不能与 /gl 一起使用", however, "/ZI" and "/Zi" are not the same. In fact, /ZI cannot be used with /GL but /Zi can be used with /GL.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 8523cfca-780b-de2e-4fc0-59a708589fc8
* Version Independent ID: d3740de2-4523-5fee-642b-1b459cc9cfee
* Content: [/GL（全程序优化）](https://docs.microsoft.com/zh-cn/cpp/build/reference/gl-whole-program-optimization?view=msvc-160#feedback)
* Content Source: [docs/build/reference/gl-whole-program-optimization.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/build/reference/gl-whole-program-optimization.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@fililili 
Thanks for the issue report. I've fixed the formatting in the source file so it's localized correctly. It may take a few days for the translated version to appear.
