### ISSUE TITLE
Wrong Chinese translation

### ISSUE THREAD

**Issue by xiongnemo** [MicrosoftDocs/cpp-docs.zh-cn#22]
“类型字段字符”中，
“秒”应为‘s’
(即不翻译
![pic](https://user-images.githubusercontent.com/38759782/46520689-828e5c80-c8af-11e8-8e87-1a8a47d66a88.png)

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 78bd3fde-7eae-a126-f330-563d912a1fab
* Version Independent ID: b6f2df29-3154-05ec-4c9b-9dbd8c316dd3
* Content: [格式规范语法：printf 和 wprintf 函数](https://docs.microsoft.com/zh-cn/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2017#type)
* Content Source: [docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by LisandroSu** [comment]
你好，@xiongnemo
 
感谢你的反馈。 
 
我们正在积极查看你的评论，并会很快地再次和你取得联系。 
 
深深的祝福， 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@xiongnemo

感谢你的反馈。  

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/cpp/c-runtime-library/format-specification-syntax-printf-and-wprintf-functions?view=vs-2017#type。   

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。  

深深的祝福，  

Microsoft DOCS International Team
