### ISSUE TITLE
Wrong translations for `conventions`

### ISSUE THREAD

**Issue by SunriseFox** [MicrosoftDocs/cpp-docs.zh-cn#23]
`convention` in Chinese should be `惯例` or `规矩` or `约定`, must not be `转换` or `conversion` in English.  So the title should be `定义与惯例` . Please update.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7926add1-34fe-8a03-34c2-ce00b1679973
* Version Independent ID: 0974f84c-3856-7098-ad7f-78d03fb049a4
* Content: [定义和转换](https://docs.microsoft.com/zh-cn/cpp/c-language/definitions-and-conventions?view=vs-2017)
* Content Source: [docs/c-language/definitions-and-conventions.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/c-language/definitions-and-conventions.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by LisandroSu** [comment]
Hello, @SunriseFox
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @SunriseFox
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @SunriseFox, 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/cpp/c-language/definitions-and-conventions?view=vs-2017. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
