### ISSUE TITLE
Chinese version typo

### ISSUE THREAD

**Issue by EtoDemerzel0427** [MicrosoftDocs/cpp-docs.zh-cn#32]
Your Chinese documentation：
character-constant: ' c-char-sequence '
L” c-char-sequence “

However the second line should be L'c-char-sequence'. Pls fix this typo.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 059e00c1-a63b-227f-c4ff-6ce282992cc5
* Version Independent ID: 595fcad1-7d47-8d0b-fb3b-829e573c5249
* Content: [C 字符常量](https://docs.microsoft.com/zh-cn/cpp/c-language/c-character-constants?view=vs-2017)
* Content Source: [docs/c-language/c-character-constants.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/c-language/c-character-constants.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by LisandroSu** [comment]
Hello, @EtoDemerzel0427 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by EtoDemerzel0427** [comment]
> Hello, @EtoDemerzel0427
>  
> Thank you for your feedback.
>  
> We are actively reviewing your comments and will get back to you soon.
> 
> Kind regards,
> Microsoft DOCS International Team

I noticed it is now fixed, so this issue could be closed. Thanks for your immediate response.
