### ISSUE TITLE
怎么错了

### ISSUE THREAD

**Issue by GD-GK** [MicrosoftDocs/cpp-docs.zh-cn#37]
[在此处输入反馈]
#include <iostream>
using namespace std;
struct Person
{
	string name;
	int count;
};
int main()
{
	Person candidate[3] = { "张三",0,"李四",0,"王五",0 };
	string vote[10] = { "张三","张三","王五","李四", "张三","王五", "张三","李四" ,"张三","王五" };
	for (int i = 0; i < 10; i++)
	{
		for (int j = 0; j < 3; j++)
			if (vote[i] == candidate[j].name)
				candidate[j].count++;
	}
	for (int i = 0; i < 3; i++)
	{
		cout << candidate[i].name << ":" << candidate[i].count << endl;
	}
	system("pause");
	return 0;
}

严重性	代码	说明	项目	文件	行	禁止显示状态	详细说明
错误(活动)	E0349	没有与这些操作数匹配的 "<<" 运算符	第七章 自定义数据类型	C:\Users\ee5e5e5\Desktop\我爱你C++PTT上的\第七章 自定义数据类型\第七章 自定义数据类型\7-1-计票(p13).cpp	20		            操作数类型为:  std::ostream << std::string

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: e5b47b53-bad6-2060-2efd-bc81ff7af82c
* Version Independent ID: 2deaf7ac-6f96-1cc4-0414-8267e70e7f1f
* Content: [编译器错误 C2679](https://docs.microsoft.com/zh-cn/cpp/error-messages/compiler-errors-2/compiler-error-c2679?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DZH-CN%26k%3Dk(C2679)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/error-messages/compiler-errors-2/compiler-error-c2679.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/error-messages/compiler-errors-2/compiler-error-c2679.md)
* Product: **visual-cpp**
* GitHub Login: @v-anpasi

**Comment by CeciAc** [comment]
你好，@GD-GK

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
