### ISSUE TITLE
想快速得到需要的结果却始终没有找到！

### ISSUE THREAD

**Issue by wxyGitHub20181128** [MicrosoftDocs/cpp-docs.zh-cn#43]
[在此处输入反馈]
没有一个例子说明怎样做一个批处理文件，打开命令行窗口，然后执行编译链接生成可执行文件；

我实验的结果是只能打开，配置环境，但没能编译！

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fbe5bf92-274e-ebfd-401e-f3740dd60644
* Version Independent ID: de36ca5c-c165-9d48-bbe5-2e3e17afbbb5
* Content: [演练： 创建标准 c + + 程序 （c + +）](https://docs.microsoft.com/zh-cn/cpp/windows/walkthrough-creating-a-standard-cpp-program-cpp?view=vs-2017)
* Content Source: [docs/windows/walkthrough-creating-a-standard-cpp-program-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/windows/walkthrough-creating-a-standard-cpp-program-cpp.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #577](https://github.com/MicrosoftDocs/cpp-docs/issues/577) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
你好，@wxyGitHub20181128

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://github.com/MicrosoftDocs/cpp-docs/issues/577。 

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
