### ISSUE TITLE
为什么我用批处理文件创建自己的命令提示窗口编译hello.c文件怎么做都不成功，问题出在哪里？

### ISSUE THREAD

**Issue by wxyGitHub20181128** [MicrosoftDocs/cpp-docs.zh-cn#44]
即使我以超级管理员登陆win10(家庭版)，用批处理文件可以打开命令提示窗口，
第一行是：%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2017  \Community\VC\Auxiliary\Build\vcvars64.bat"成功配置64位环境，但之后什么也不做了，不过要是手动继续操作，编译命令仍然能成功生成*.exe可执行文件，这到底是什么地方不正确？

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 45e8226e-799c-2e3b-01c6-d7603141d5ca
* Version Independent ID: 4f7cd478-ffcc-bec5-b61a-e17085ccd6f5
* Content: [在命令行上生成 C/c + + 代码](https://docs.microsoft.com/zh-cn/cpp/build/building-on-the-command-line?view=vs-2017)
* Content Source: [docs/build/building-on-the-command-line.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/build/building-on-the-command-line.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
你好，@wxyGitHub20181128

非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
