### ISSUE TITLE
在vs2017上无法关闭/Zc:strictStrings

### ISSUE THREAD

**Issue by lyrii** [MicrosoftDocs/cpp-docs.zh-cn#55]
在vs2017的属性页-命令行-其他选项中添加/Zc:strictStrings- 没有效果。const char*还是不能转换为char*。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7a87a824-a67a-63bb-3cfe-c72538388115
* Version Independent ID: 50d0ef7e-c093-2d63-4ba8-d8e566dfd2fb
* Content: [/Zc:strictStrings（禁用字符串文本类型转换）](https://docs.microsoft.com/zh-cn/cpp/build/reference/zc-strictstrings-disable-string-literal-type-conversion?view=vs-2017)
* Content Source: [docs/build/reference/zc-strictstrings-disable-string-literal-type-conversion.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/build/reference/zc-strictstrings-disable-string-literal-type-conversion.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
你好，@lyrii
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
