### ISSUE TITLE
How to set  YASM compile Command Line in Custom Build Setp?

### ISSUE THREAD

**Issue by neobull2005** [MicrosoftDocs/cpp-docs.zh-cn#67]
In windows,  I use  Command Line like "vsyasm -I..\..\common\x86\ -f win64 -m amd64 -O0 -o "$(IntDir)%(Filename)".obj "%(FullPath)" to use YASM compile *.asm file.  Now I  use Visual Studio 2017 to complie  Linux project with  *.asm (YASM ) , how to set Command Line of  YASM  in Custom Build Setp?  

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 58974a09-7174-d295-5181-9df4a7370c23
* Version Independent ID: 5faf7df8-3128-fda4-05f2-e1a9eff590f3
* Content: [自定义生成步骤属性 (Linux C++)](https://docs.microsoft.com/zh-cn/cpp/linux/prop-pages/custom-build-step-linux?view=vs-2017#feedback)
* Content Source: [docs/linux/prop-pages/custom-build-step-linux.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/linux/prop-pages/custom-build-step-linux.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
Hello, @neobull2005 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
