### ISSUE TITLE
How can I reset all project properties?

### ISSUE THREAD

**Issue by 1069066484** [MicrosoftDocs/cpp-docs.zh-cn#70]
It seems I have messed up relative settings of project properties. Now, I cannot build X86 solutions anymore, even the most simple C++ codes( but it is ok to build X64 solutions). The error says "module machine type 'x86' conflicts with target machine type 'x64'".  Now, I am thinking about resetting all properties, including VC++ directories, and all other settings in the property pages. I tried reinstall VS and the "Reset all settings" tool, but they do not work. So, any suggestion? Thanks.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: a7beb1d6-9b03-5440-1dd3-99148a22d5cc
* Version Independent ID: 080c3597-2275-a711-d265-c6d7f41db618
* Content: [.vcxproj 和 .props 文件结构](https://docs.microsoft.com/zh-cn/cpp/ide/vcxproj-file-structure?view=vs-2017#feedback)
* Content Source: [docs/ide/vcxproj-file-structure.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/ide/vcxproj-file-structure.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
Hello, @1069066484 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
