### ISSUE TITLE
装不上g++

### ISSUE THREAD

**Issue by yinhx3** [MicrosoftDocs/cpp-docs.zh-cn#77]
错误提示：
Ign:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 linux-libc-dev amd64 4.15.0-29.31
Err:1 http://security.ubuntu.com/ubuntu bionic-updates/main amd64 linux-libc-dev amd64 4.15.0-29.31
  404  Not Found [IP: 2001:67c:1360:8001::17 80]
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_4.15.0-29.31_amd64.deb  404  Not Found [IP: 2001:67c:1360:8001::17 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: cb0acbb6-5b9f-b28d-a7c8-196049ee561f
* Version Independent ID: c77469e1-7c9f-3dcd-c2e5-63c75f160e1a
* Content: [在 Visual Studio 中安装 C++ Linux 工作负载](https://docs.microsoft.com/zh-cn/cpp/linux/download-install-and-setup-the-linux-development-workload?view=vs-2019#feedback)
* Content Source: [docs/linux/download-install-and-setup-the-linux-development-workload.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/linux/download-install-and-setup-the-linux-development-workload.md)
* Product: **visual-cpp**
* Technology: **cpp-linux**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
你好，@yinhx3
非常感谢你的参与。我们的团队只能回应与文档相关的反馈。 

请使用 DOCS 页面底部的“提供产品反馈”按钮记录你的产品反馈。 

若有与文档相关的任何反馈，欢迎通过此通道将它记录下来。 

非常感谢你对我们的文章作出的贡献。  

深深的祝福， 
Microsoft DOCS International Team
