### ISSUE TITLE
“子句”链接指向了“指令页面”

### ISSUE THREAD

**Issue by UnitDan** [MicrosoftDocs/cpp-docs.zh-cn#88]
“子句”链接指向了“指令页面”

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ef561fb5-bc2c-d281-9f5b-9d52fa612f12
* Version Independent ID: ed0f2280-f9f8-5ba7-c8d6-dcdd81918485
* Content: [OpenMP 库参考](https://docs.microsoft.com/zh-cn/cpp/parallel/openmp/reference/openmp-library-reference?view=vs-2019&tdsourcetag=s_pcqq_aiomsg#feedback)
* Content Source: [docs/parallel/openmp/reference/openmp-library-reference.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/parallel/openmp/reference/openmp-library-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by CeciAc** [comment]
你好，@UnitDan

非常感谢你的参与。你的反馈与原始文档有关。 

因此，我们会将此问题迁移到英文版存储库。请在这里查看问题的状态 - https://docs.microsoft.com/zh-cn/cpp/parallel/openmp/reference/openmp-library-reference?view=vs-2019&tdsourcetag=s_pcqq_aiomsg

非常感谢你对我们的文章作出的贡献。  


深深的祝福， 
Microsoft DOCS International Team
