### ISSUE TITLE
标题翻译异常

### ISSUE THREAD

**Issue by XieEDeHeiShou** [MicrosoftDocs/cpp-docs.zh-cn#97]
"C/C++ projects and build systems in Visual Studio" 被翻译为了
"Visual StudioC++中的 C/项目和生成系统"

更适当的译文是 "Visual Studio 中的 C/C++ 项目和生成系统"

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: fd8973bd-ab25-4497-e05b-e690fe6060d5
* Version Independent ID: ebc36c82-e305-d5e1-ac17-3c55e2944d56
* Content: [Visual StudioC++中的 C/项目和生成系统](https://docs.microsoft.com/zh-cn/cpp/build/projects-and-build-systems-cpp?view=vs-2019#feedback)
* Content Source: [docs/build/projects-and-build-systems-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/build/projects-and-build-systems-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @XieEDeHeiShou
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
你好，@XieEDeHeiShou

感谢你的反馈。 

我们语言专家团队已评审并接受你的语言相关建议。我们已实施你的反馈，并将更新后的文章发布到 Docs 站点上的以下页面：https://docs.microsoft.com/zh-cn/cpp/build/projects-and-build-systems-cpp?view=vs-2019#feedback

非常感谢你对我们的文章作出的贡献，欢迎继续提供宝贵的反馈。 


深深的祝福， 

Microsoft DOCS International Team
