### ISSUE TITLE
The value range of int64 for chinese preview is wrong

### ISSUE THREAD

**Issue by tianhanghai** [MicrosoftDocs/cpp-docs.zh-cn#99]
The value range of int64  in language of Chinese is wrong.  
In English,its range is [-9,223,372,036,854,775,808 , 9,223,372,036,854,775,807].
In Chinese,its range is [-9,223,372,036,854 , 9223372036854775807 775,808].

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 7374927a-30ae-8f67-f788-5cb1a5bb0feb
* Version Independent ID: 40e8f805-d133-8fa1-9f7b-c07176dd37ed
* Content: [基本类型 (C++/CX)](https://docs.microsoft.com/zh-cn/cpp/cppcx/fundamental-types-c-cx?view=vs-2019#feedback)
* Content Source: [docs/cppcx/fundamental-types-c-cx.md](https://github.com/MicrosoftDocs/cpp-docs.zh-cn/blob/live/docs/cppcx/fundamental-types-c-cx.md)
* Product: **visual-cpp**
* Technology: **cpp-cx**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @tianhanghai
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @tianhanghai 

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/zh-cn/cpp/cppcx/fundamental-types-c-cx?view=vs-2019#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
